### PR TITLE
chore: Prepare release 0.1.3

### PR DESCRIPTION
**Pull request by w-vi**
- ignore flake8 error

### CODE REVIEW

**Comment by honzajavorek** [comment]
What was the linter error? If it complains that `e` is unused variable, couldn't it be solved by not creating the variable? Just from the top of my head.

```python
except Exception:
```

**Comment by w-vi** [comment]
Ha! Switching between languages makes one think the wrong way! :)

**Comment by w-vi** [comment]
@honzajavorek comments addressed.

**Comment by w-vi** [comment]
Will tag and release.

**Pull request merged**
