### PR TITLE
Drop Circle CI testing

### PR DESCRIPTION
**Pull request by w-vi**

### CODE REVIEW

**Comment by netmilk** [comment]
Lol image

**Comment by netmilk** [comment]
Last time I was trying to remove circle from some project it was a pita. I recall I had to remove it from webhooks in the repository settings.

**Comment by w-vi** [comment]
I asked on Circle's support how to do it properly as I haven't found any easy way.

**Comment by w-vi** [comment]
@netmilk Please review and merge, cheers. :bee:

**Comment by netmilk** [comment]
@w-vi Haha, I asked their support about same thing a month ago and the answer was everyone in the organisation has to unfollow the project... So it's a team task.

**Comment by honzajavorek** [comment]
OMG :see_no_evil:

**Pull request merged**
