### PR TITLE
Integration test aruba

### PR DESCRIPTION
**Pull request by w-vi**
see
[dredd-hooks-templaterepo](https://github.com/apiaryio/dredd-hooks-template)
for details of the test.

- circle CI uses aruba too
- changes in dredd_hooks to conform to aruba test
- update README and fix typos and errors
- AddTravis CI

### CODE REVIEW

**Comment by w-vi** [comment]
@honzajavorek can you have a look, please?

**Comment by w-vi** [comment]
@honzajavorek : Circle is down so don't bother with it, Travis runs the same tests.

**Comment by honzajavorek** [comment]
Finished my review :microscope: Looks good. I had some nitpicks, but nothing to turn down your PR in this stage of development. Cheers! :tada:

**Comment by honzajavorek** [comment]
Code looks good, TravisCI tests passed, CircleCI is down. Merging! :snake:

**Comment by w-vi** [comment]
@honzajavorek I hope I have addressed all comments to your satisfaction :)

**Comment by honzajavorek** [comment]
satisfaction

**Comment by kylef** [comment]
CircleCI did fail with these changes, you can find a failing build at https://circleci.com/gh/apiaryio/dredd-hooks-python/54 causing #6 to be red.

**Comment by w-vi** [comment]
Rebuilt without cache and it is green again ... I will probably get rid of circle anyway.

**Comment by netmilk** [comment]
> I will probably get rid of circle anyway.
+1 one or other... :)

**Comment by honzajavorek** [comment]
If having two CIs, it's probably worth to employ appveyor.com like blueprint team does to test builds on Windows rather than having both Circle and Travis.

**Comment by netmilk** [comment]
@honzajavorek Dredd is not Windows ready, yet :( https://github.com/apiaryio/dredd/issues/204

**Comment by honzajavorek** [comment]
Meow :crying_cat_face:

**Comment by w-vi** [comment]
There's no point having 2 almost identical CIs ... I jumped to Travis while Circle was down for hours and will stick with it as the rest of `dredd system` is using it.

**Pull request merged**
