### PR TITLE
Implement handler options

### PR DESCRIPTION
**Pull request by TotempaaltJ**
As mentioned in #29, these weren't implemented, and they'd be useful for us so I figured I'd just do it now :)

### CODE REVIEW

**Comment by w-vi** [comment]
:+1: 

Thanks a lot! Just one thing the names of the arguments for the hook handlers are `--host` and `--port`, see https://github.com/apiaryio/dredd-hooks-template/pull/17#issuecomment-279980408 . The names you have used are in dredd itself. Please rename them so that it is in line with others. Cheers.

**Comment by w-vi** [comment]
Oh and please squash the commits as this is one logical change. Thanks a lot.

**Comment by TotempaaltJ** [comment]
Oops, misread the issue. I'll fix that yeah :)

**Comment by w-vi** [comment]
@TotempaaltJ Thanks a lot! I suppose there will be a release soon.

**Pull request merged**
